project:
  type: book
  output-dir: _build
  preview:
    port: 6833 # use the same port instead of a new one each time
    browser: true

# https://quarto.org/docs/books/
# https://quarto.org/docs/reference/projects/books.html
book:
  title: "Predictive Modeling in Python"
  author: "Michael J Rossetti"
  date: "last-modified" # "7/24/2024"
  date-format: "iso"
  #doi: "...."
  #isbn: "..."
  #issn: "..."
  #edition: "v2"

  site-url: https://prof-rossetti.github.io/predictive-modeling-python-book/
  repo-url: https://github.com/prof-rossetti/predictive-modeling-python-book/
  repo-branch: main
  repo-subdir: docs
  repo-actions: [edit, issue, source]
  #downloads: [pdf, epub, docx]

  #cover-image: images/predictive-modeling-book-banner.png
  #favicon: favicon.ico

  #sharing: [twitter, facebook]

  # https://quarto.org/docs/websites/website-tools.html#open-graph
  #open-graph: true

  # https://quarto.org/docs/websites/website-tools.html#google-analytics
  # doesn't work for github pages?
  # see html: include-in-header option at bottom instead ..
  # jk use tracking id as well?
  # https://github.com/quarto-dev/quarto-cli/discussions/9065
  #google-analytics:
  #  tracking-id: "G-...."
  # jk still doesn't work. see include-in-header option ...

  # https://quarto.org/docs/reference/projects/books.html#search
  search: #true
    location: sidebar # navbar, sidebar
    #type: textbox # overlay, textbox

  #navbar:
  #  right:
  #    - href: exercises/index.qmd
  #      text: "Exercises, Assignments, and Projects"
  #    - about-author.qmd

  # https://quarto.org/docs/websites/website-navigation.html#side-navigation
  sidebar:
    logo: images/predictive-modeling-book-banner-2025.png

  #page-footer:
  #  left: |
  #    Copyright 2024, <a href="https://prof-rossetti.org/">Michael J Rossetti</a>
  #  right: |
  #    This book was built with <a href="https://quarto.org/">Quarto</a>.



  chapters:
    - index.qmd
    - notes/predictive-modeling.qmd

    - "-------------"
    - part: "Machine Learning Foundations"
      chapters:
        - href: notes/ml-foundations/index.qmd
          text: "Machine Learning Overview"

        - href: notes/ml-foundations/generalization.qmd
          text: "Generalization"

        - href: notes/ml-foundations/data-encoding.qmd
          text: "Data Encoding"

        - href: notes/ml-foundations/data-scaling.qmd
          text: "Data Scaling"

    - "-------------"
    #- href: notes/supervised-learning.qmd
    #  text: "Supervised Learning Overview"

    - part: "Regression"
      chapters:
        - href: notes/regression/index.qmd
          text: "Regression Overview"

        - href: notes/regression/linear.qmd
          text: "Linear Regression"

        - href: notes/regression/ols.qmd
          text: "Linear Regression w/ `statsmodels`"

        - href: notes/regression/multiple-features.qmd
          text: "Regression with Multiple Features"

        #- href: notes/regression/ridge-lasso.qmd
        #  text: "Regression with Regularization (Ridge and Lasso)"

    - "-----------"

    - part: "Regression for Time-series Forecasting"
      chapters:
        - href: notes/time-series-forecasting/index.qmd
          text: "Time-series Forecasting Overview"

        - href: notes/time-series-forecasting/polynomial.qmd
          text: "Polynomial Features"

        - href: notes/time-series-forecasting/seasonality.qmd
          text: "Seasonality Analysis"


    - part: "Autoregressive Models for Time-series Forecasting"
      chapters:
        #- href: notes/autoregressive-models/index.qmd
        #  text: "Autoregressive Models Overview"

        - href: notes/autoregressive-models/stationarity.qmd
          text: "Stationarity"

        - href: notes/autoregressive-models/autocorrelation.qmd
          text: "Autocorrelation"

        - href: notes/autoregressive-models/arima.qmd
          text: "Autoregressive Models w/ `statsmodels`"

    - "-----------"
    - part: "Classification"
      chapters:
        - href: notes/classification/index.qmd
          text: "Classification Overview"

        #- href: notes/classification/logistic.qmd
        #  text: "Logistic Regression"

        #- href: notes/classification/binary.qmd # edit the qmd and convert to ipynb for github actions:
        - href: notes/classification/binary.ipynb
          text: "Binary Classification"

        #- href: notes/classification/multiclass.qmd
        #  text: "Multi-class Classification"

        #- href: notes/classification/Spam_Detection_(Binary_Classification)_SOLUTIONS.ipynb
        #  text: "Binary Classification w/ `sklearn`"
#
        #- href: notes/classification/Penguins_Classifier_(Multiclass)_SOLUTIONS.ipynb
        #  text: "Multiclass Classification w/ `sklearn`"


    #- part: "Natural Language Processing"
    #  chapters:
    #    - href: notes/natural-language-processing/index.qmd
    #      text: "NLP Overview"


    #      #- "--------------"
    #      - section:
    #        href: notes/predictive-modeling/unsupervised-learning.qmd
    #        text: "Unsupervised Learning"
    #        contents:
#
    #          - section:
    #            href: notes/predictive-modeling/dimensionality-reduction/pca.qmd
    #            text: "Dimensionality Reduction"
#
    #          - section:
    #            href: notes/predictive-modeling/clustering/index.qmd
    #            text: "Clustering"
#
#
    #      #- "--------------"
    #      - section:
    #        href: notes/predictive-modeling/model-management/index.qmd
    #        text: "Model Management"
    #        contents:
    #          - section:
    #            href: notes/predictive-modeling/model-management/saving-loading.qmd
    #            text: "Model Management"
    #          - section:
    #            href: notes/predictive-modeling/model-management/deploying.qmd
    #            text: "Model Deployment"
    #          - section:
    #            href: notes/predictive-modeling/model-optimization/grid-search.qmd
    #            text: "Model Optimization"







    - "-----------------"
    - about-author.qmd
    - "-----------------"

  #appendices:
  #
  #  - part: "Custom Functions In-Depth"
  #    chapters:
  #      - notes/python-lang/control-flow/function-docs.qmd
  #      - notes/python-lang/control-flow/unit-testing.qmd


  # shows up at bottom of page
  #body-footer: "&copy; Copyright 2024, Your Name Here"

  page-footer:
    center: "&copy; Copyright 2024, Michael J Rossetti"


bibliography: references.bib

format:
  html:
    # https://quarto.org/docs/output-formats/html-themes.html
    # https://bootswatch.com/
    theme: pulse
      #light: default #flatly
      #dark: darkly
    css: styles/my-style.css
    code-copy: true
    #code-fold: false #show
    ##code-line-numbers: true
    toc: true
    #toc-depth: 4 # specify the number of section levels to include in the table of contents
    toc-expand: true # show x levels initially
    ##toc-location: left
    ##number-sections: false
    ##number-depth: 1

    # https://quarto.org/docs/reference/formats/html.html#includes
    #include-in-header:
    #  text: |
    #    <!-- Google tag (gtag.js) -->
    #    <script async src="https://www.googletagmanager.com/gtag/js?id=G-...."></script>
    #    <script>
    #      window.dataLayer = window.dataLayer || [];
    #      function gtag(){dataLayer.push(arguments);}
    #      gtag('js', new Date());
    #
    #      gtag('config', 'G-....');
    #    </script>

  # THIS IS NOT WORKING YET ON GITHUB ACTIONS
  #pdf:
  #  documentclass: scrreprt
  #
  #epub:
  #  toc: true # include a table of contents
  #  cover-image: images/predictive-modeling-book-banner.png
  #  number-sections: true # number the sections
  #  #css: "custom-epub.css"
  #  embed-fonts: true
  #  metadata:
  #    identifier: "urn:isbn:1234567890" # replace with actual ISBN or identifier
  #    publisher: "Publisher Name"
  #    rights: "© 2024 Your Name. All rights reserved."
  #
  #docx:
  #  #reference-doc: "custom-reference.docx" # optional reference document for styling
  #  number-sections: true # number the sections
  #  toc: true # include a table of contents
  #  toc-depth: 2 # control depth of table of contents
  #  embed-fonts: true # embed fonts in the DOCX


  pdf:

    # use XeLaTeX or LuaLaTeX so fontspec works:
    latex-engine: xelatex

    mainfont: "Source Sans 3" # "Merriweather"
    sansfont: "Source Sans 3" # "Helvetica Neue"
    monofont: "Menlo"
    #fontsize: 11pt
    #linestretch: 1.2

    includes:
      in-header: _pdf_styles.tex

  #PrettyPDF-pdf:
  #  keep-tex: true
